#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '👷 Checking your commit message'

npx commitlint --edit $1 ||
(
    echo '🤢🤮🤢🤮 Your commit message looks disgusting. 🤢🤮🤢🤮';
    false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
